### ISSUE TITLE
Question about `maskType`

### ISSUE THREAD

**Issue by alanvww** [ml5js/ml5-next-gen#153]
Hello team! While I am working on the methods of the doc, I realize that in the examples of BodySegmentation, the same `maskType` for `BodyPix` and `SelfieSegmentation` have a totally different output. For example, 
![CleanShot 2024-06-21 at 16 25 56@2x](https://github.com/ml5js/ml5-next-gen/assets/10086000/943cf4da-a643-46d7-b9ea-d86bdbfdf091)
This is `SelfieSegmentation` with `person`
![CleanShot 2024-06-21 at 16 26 16@2x](https://github.com/ml5js/ml5-next-gen/assets/10086000/b6af4db1-6941-4bb3-9b62-1ba1c3d94ddb)
And this is `BodyPix` with `person`. 

There is no explanation for this in the previous doc, and I was trying to differentiate these two mask types with these two models in the new reference. 

@ziyuan-linn @shiffman @MOQN

**Comment by ziyuan-linn** [comment]
@alanvww thank you for letting me know about this! I believe this is a bug, I will investigate further.

In the meantime, the correct behavior should be:
- `maskType: person`: the person is covered by the mask
- `maskType: background:` the background is covered by the mask

**Comment by alanvww** [comment]
> @alanvww thank you for letting me know about this! I believe this is a bug, I will investigate further.
> 
> In the meantime, the correct behavior should be:
> 
> * `maskType: person`: the person is covered by the mask
> * `maskType: background:` the background is covered by the mask

Got it! Also, Do we keeping `maskType: parts` and I believe it is `BodyPix` only?

**Comment by ziyuan-linn** [comment]
Yes, we will keep `maskType: parts`, and it is `BodyPix` only.

Could you please share a link to the p5 example sketch? I am not able to recreate the bug.

**Comment by alanvww** [comment]
- [https://editor.p5js.org/ml5/sketches/h6TN8umP5](https://editor.p5js.org/ml5/sketches/h6TN8umP5)
- [https://editor.p5js.org/ml5/sketches/ruoyal-RC](https://editor.p5js.org/ml5/sketches/ruoyal-RC)

The screenshots were these two sketches and I change the BodyPix one to use masktype:person and it works but the opposite of SelfieSegmentation.

The reason why I did this is because the old doc never mention if they are some model only or not, so I want to try it to see the result.

**Comment by ziyuan-linn** [comment]
Thank you for the clarification! 

I apologize for the lack of documentation on this, here is what's going on:

When `maskType` is `person`, `result.mask` is an image with black pixels on the background and transparent pixels on the person. We use the [p5 mask function](https://p5js.org/reference/#/p5.Image/mask) to mask the p5 webcam video (apply the image's alpha onto the frame of the video), the person becomes transparent the video frame.

When `maskType` is `background`,  `result.mask` is an image with black pixels on the person and transparent pixels on the background. Applying the mask to the video makes the background transparent.

When `maskType` is `parts`, `result.mask` is an image with white pixels on the background and various color pixels for each body part. p5's `mask` function is not very useful in this case since the mask is not transparent at all.

The first example you sent uses the p5 `mask` function in `draw` and the second example you sent uses the p5 `image` function in `draw`, which is why `maskType: parts` showed up as black pixels on the background.

-----
Here is an update made by @gohai yesterday, adding more properties to `result` and making the parts mask more useful: https://github.com/ml5js/ml5-next-gen/pull/139. If there is not enough time to document these new changes on the website, I think we can focus on documenting `result.mask` and all more information after the release tomorrow.

**Comment by alanvww** [comment]
@ziyuan-linn Ohhhh I see what you mean. I just checked the sketches and I think the "bug" I experienced is exactly the different usage of using p5.mask with the video or not. That makes so much sense now. Sorry for the false alarm!

Btw, some comments in the source code might also be wrong, if you can check with that would be fantastic :D
