### ISSUE TITLE
FaceMesh faceOval points not in order around the face

### ISSUE THREAD

**Issue by dano1234** [ml5js/ml5-next-gen#67]
Here is a sketch with old ML5 facemesh making a mask
https://editor.p5js.org/dano/sketches/2ULaz2E0v

Here is a sketch with  new ML5 facemesh making a mask
https://editor.p5js.org/dano/sketches/-3gKqxIZD

It appears that all the points for the "faceOval" property come in but they are not in a consecutive order around the face.

As ever thanks for this amazing library

**Comment by ziyuan-linn** [comment]
Sounds great! I am happy to look into this. 

I think the original facemesh came with an annotations object but the new one didn't, so we are now manually creating the annotations within ml5. Apparently, we forgot to take the order of the vertices into account. I will take a look at the old tfjs facemesh library to see how they generate the annotations object.

In addition to using a vertex-sorting algorithm, we could also consider manually creating a map so we can sort the vertices in linear time.

**Comment by gohai** [comment]
Thanks for the report @dano1234! This didn't come up, wasn't attempted, in the summer.

Turns out that MediaPipe, the new underlying model, returns points in a particular order, but for creating contours, we can't simply pair them up sequentially. [Here is how](https://github.com/tensorflow/tfjs-models/blob/master/face-landmarks-detection/demos/shared/util.js#L207C22-L207C75) Google's own implementation gets this done. And [this](https://github.com/tensorflow/tfjs-models/blob/master/face-landmarks-detection/src/constants.ts) is the source of these pairings. We should amend `addKeypoints` to take care of this for the contours it creates.

@ziyuan-linn @shiffman I'd be happy to address this Saturday morning (unless Peter already fixed this while I am writing this message 😅)

**Comment by gohai** [comment]
@dano1234 Should be fixed in upcoming test builds! (Here's a [preview](https://editor.p5js.org/gohai/sketches/UzCYkm9Zr) using a local ml5.js.)

We did change the API since the initial build: the points moved to `.keypoints`, so that every contour also has an (easier to use) `.centerX`, `.centerY` properties etc..
