### ISSUE TITLE
CDN for ml5.js release

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-next-gen#88]
This is the section as I have it in the Nature of Code book:

<img width="687" alt="Screen Shot 2024-03-12 at 6 16 30 PM" src="https://github.com/ml5js/ml5-next-gen/assets/191758/78d9450b-18e5-43a3-8beb-298773db6441">

I tend to prefer to reference a specific version for use with the examples in case things change, but since we aren't sure what the version # will be for the upcoming release maybe putting `latest` in is best? @ziyuan-linn any reason you anticipate this changing once we publish to npm? 

Shall I leave as is or any thoughts?

**Comment by ziyuan-linn** [comment]
I'm excited about the new Nature of Code publish!

Assuming we follow [Semantic Versioning standards](https://semver.org/) for all future releases, we probably have two options for the next version number, `1.0.0` or `0.20.0`.

If we release version `1.0.0`, I think `https://unpkg.com/ml5@^1.0.0/dist/ml5.min.js` would be a good URL. It will upgrade to the latest `1.X.X` release, including future bug fixes and backward-compatible changes but excluding breaking changes.

I remember having a discussion a while ago about versioning and not everyone was comfortable with making the `1.0.0` release yet. In that case, our next version should be `0.20.0` since we are in `0.20.0-alpha` now. Then `https://unpkg.com/ml5@~0.20.0/dist/ml5.min.js`, upgrading to the latest `0.20.X` release, would probably be the best bet.

These are just my thoughts! Perhaps we can bring up versioning again during Thursday's meeting?

**Comment by shiffman** [comment]
That's a great idea, let's discuss this in the meeting on Thursday!

**Comment by gohai** [comment]
Seconding @ziyuan-linn's suggestion to use `1.0.0` and semantic versioning that picks the latest minor/patch release within the same major number.

I believe these (shorter) URLs should also work (equivalently), but perhaps someone might want to double-check: `https://unpkg.com/ml5@^1/dist/ml5.min.js` or `https://unpkg.com/ml5@1/dist/ml5.min.js`.

The benefit with the latter (_if_ it works, which it [seems](https://unpkg.com/@gohai/p5.webserial@1/libraries/p5.webserial.js) to be doing on a package of mine) is that it'd avoid the caret character, which is a bit unhandy to use, as it apparently technically wants to get encoded as `%5e` when part of a URL.

**Comment by shiffman** [comment]
Allright, all makes sense to me! I'll go with `https://unpkg.com/ml5@1.0.0/dist/ml5.min.js` in the book (@gohai there's plenty of space on the page so I don't need to shorten it). . .and now we have an actual deadline for when we have to publish this version by! (summer? but maybe sooner!)

**Comment by gohai** [comment]
@shiffman unless I am mistaken, `ml5@1.0.0` would always refer to the particular version (without the possibility of addressing bugs etc) - `ml5@^1.0.0` nicer?

**Comment by shiffman** [comment]
oh, good point! Yes, that makes sense I forgot about `^`

**Comment by shiffman** [comment]
Actually I think it's `@` not `^`, tested with some other libraries, this should work!

`https://unpkg.com/ml5@1/dist/ml5.min.js`

**Comment by gohai** [comment]
@shiffman I think so. Believe `ml5@1` will spark joy - just the `ml5@1.0.0` wouldn't
